version: "3.1"

services:
  api:
    container_name: summary
    build:
      context: .
    command: python main.py
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"
    ports:
      - 8000:8000
    volumes:
      - .:/app

networks:
  botnet:
    driver: bridge
